### PR TITLE
WIP: factor out routes

### PR DESCRIPTION
**Pull request by tpolecat**
This factors out the GraphQL routing infrastructure into a new [lucuma-graphql-routes](https://github.com/gemini-hlsw/lucuma-graphql-routes) project, so we can use it with all our services.

### CODE REVIEW

**Review by swalker2m — COMMENTED** [review]
Looks good, pending dependency publication.

**Comment by tpolecat** [comment]
Ok this is ready for review.

**Comment by tpolecat** [comment]
Cool, I'll let you merge when it's convenient.

**Comment by swalker2m** [comment]
I'm not doing anything in this repo right now since I'm worried with `ocs` stuff.  @toddburnside @cquiroz @rpiaggio  Anybody else object to merging now?

**Pull request merged**
