### PR TITLE
active status

### PR DESCRIPTION
**Pull request by swalker2m**
Adds the observation "active" status corresponding to https://github.com/gemini-hlsw/lucuma-core/pull/349

I'm not happy with the name "active" for the field and mutation.  To set it to inactive you have to add, for example,

```
 "updateObservation": {
    "observationId": "o-2",
    "active": "INACTIVE"
  }
```

which seems weird.  Suggestions on a better name appreciated.

### CODE REVIEW

**Review by rpiaggio — APPROVED** [review]
LGTM

**Comment by rpiaggio** [comment]
> I'm not happy with the name "active" for the field and mutation.

How about `activeStatus`?

**Comment by swalker2m** [comment]
> How about `activeStatus`?

That's probably better.  Still, we'd have `status` (which is the observation status: for review, for activation, etc.) and `activeStatus`.

**Comment by toddburnside** [comment]
> > How about `activeStatus`?
> 
> That's probably better. Still, we'd have `status` (which is the observation status: for review, for activation, etc.) and `activeStatus`.

`activeState`?

**Review by toddburnside — APPROVED** [review]
LGTM

**Comment by swalker2m** [comment]
Renamed to `activeStatus`.

**Pull request merged**
